version: '3.8'

services:
  backend:
    image: dbillion/harvestconnect-backend:latest
    container_name: harvestconnect-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    env_file:
      - ./backend/.env
    networks:
      - harvestconnect-network
    restart: unless-stopped

  frontend:
    image: dbillion/harvestconnect-frontend:latest
    container_name: harvestconnect-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      - harvestconnect-network
    restart: unless-stopped

networks:
  harvestconnect-network:
    driver: bridge

volumes:
  db_data: