      - name: Deploy to Koyeb
        run: |
          CACHEBUST=$(date +%s)
          koyeb service update harvestconnect-backend/api \
            --git-branch main \
            --docker-args "--build-arg CACHEBUST=${CACHEBUST}" \
            --env DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
            --env DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --env ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" \
            --env CSRF_TRUSTED_ORIGINS="${{ secrets.CSRF_TRUSTED_ORIGINS }}" \
            --env ADMIN_URL_PATH="${{ secrets.ADMIN_URL_PATH }}" \
            --env STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            --env GOOGLE_GEMINI_API_KEY="${{ secrets.GOOGLE_GEMINI_API_KEY }}" \
            --env GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            --env GOOGLE_OAUTH2_CLIENT_ID="${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}" \
            --env GOOGLE_OAUTH2_CLIENT_SECRET="${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}" \
            --env GITHUB_OAUTH2_CLIENT_ID="${{ secrets.BBGITHUB_OAUTH2_CLIENT_ID }}" \
            --env GITHUB_OAUTH2_CLIENT_SECRET="${{ secrets.BBGITHUB_OAUTH2_CLIENT_SECRET }}" \
            --env DEBUG=False
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
